# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a8add4feb5b88a2ffae384ac76afa34b407357fb768db477ce5a9fab8213a063c4e8f4c6b8c46173fd0b8c10a58e90760569b7d7f0ddd3b42124126ea314516

test:
  secret_key_base: b25ed799e1b7951fb10bef7e806c297b82d7aee0a9527332a18f8d7b52e8b9bd759552ef49ff189d6de21faa0bec1e42a8a03c26c813fedbad30d9c2ffa36954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
